services:
  kanidm:
    image: kanidm/server:latest
    command: ["/sbin/kanidmd", "server", "-c", "/etc/kanidm/server.toml"]
    ports:
      - "8443:8443"
    volumes:
      - kanidm_data:/data
      - ./kanidm/server.toml:/etc/kanidm/server.toml:ro
      - ./certs:/certs:ro

volumes:
  kanidm_data:

